### PR TITLE
Added some Ideas for html,javascript,python,reactjs

### PR DESCRIPTION
**Pull request by Sulagna-Dutta-Roy**
<p>Html</p>
<ul>
<li>Simple school admission form</li>
<li>Image Gallery</li>
</ul>

<p>Javascript</p>
<ul>
<li>Fruit cutter game</li>
<li>Ping Pong game</li>
</ul>

<p>Reactjs</p>
<ul>
<li>Movie Seat Booking App</li>
<li>Frontend Pagination</li>
</ul>

<p>Python</p>
<ul>
<li>Library Management System</li>
</ul>

### CODE REVIEW

**Comment by praveenscience** [comment]
Why does it show too many changes? Can you please check @Sulagna-Dutta-Roy?

**Comment by Sulagna-Dutta-Roy** [comment]
Sure, Sir.

**Comment by praveenscience** [comment]
I really wanna merge this, can you please update this PR? It still shows conflicts. 😔

**Comment by Sulagna-Dutta-Roy** [comment]
Sir, I updated the readme. But can't solve the conflicts

**Review by rohan-kulkarni-25 — CHANGES_REQUESTED** [review]
Hey @Sulagna-Dutta-Roy  I think you made changes in branch so better option will be sync your main branch with the project and then by creating new branch just update the  name of project which you like to add ! Let this PR go empty but create a new PR so only made changes will be visible than whole file as a change

**Review by praveenscience — APPROVED** [review]
👍

**Comment by praveenscience** [comment]
Thanks for your contribution. Optional Request: [Subscribe to my **YouTube Channel**](https://www.youtube.com/praveenscience?sub_confirmation=1), if you haven't already subscribed and share it with your friends too.

**Pull request merged**
