### PR TITLE
Updated Readme.md

### PR DESCRIPTION
**Pull request by Anshu-111**
added Content Management System for a blog in Generic Stack
added  Online Distance Education System in MERN Stack
added Billing System  in Python - Django

### CODE REVIEW

**Review by praveenscience — APPROVED** [review]
👍

**Comment by praveenscience** [comment]
Thanks for your contribution. Optional Request: [Subscribe to my **YouTube Channel**](https://www.youtube.com/praveenscience?sub_confirmation=1), if you haven't already subscribed and share it with your friends too.

**Comment by Anshu-111** [comment]
Thanks 😊 Praveenscience/Hacktoberfest-Project-Ideas

**Comment by praveenscience** [comment]
Awesome, keep up the good work.

**Comment by Anshu-111** [comment]
Thank you so much

**Pull request merged**
