### PR TITLE
Added more ideas

### PR DESCRIPTION
**Pull request by vatsla1601**
* Vatsla Adhikari's idea added.

### CODE REVIEW

**Review by praveenscience — APPROVED** [review]
👍

**Comment by praveenscience** [comment]
Thanks for your contribution. Optional Request: [Subscribe to my **YouTube Channel**](https://www.youtube.com/praveenscience?sub_confirmation=1), if you haven't already subscribed and share it with your friends too.

**Comment by vatsla1601** [comment]
Thank you sir and I will continue to contribute to open source.

**Comment by praveenscience** [comment]
Awesome, keep up the good work.

**Pull request merged**
