### PR TITLE
Added Two new interesting project in python and android development

### PR DESCRIPTION
**Pull request by subhav13**

### CODE REVIEW

**Comment by subhav13** [comment]
Can I get a review?

**Review by praveenscience — APPROVED** [review]
👍

**Comment by praveenscience** [comment]
Thanks for your contribution. Optional Request: [Subscribe to my **YouTube Channel**](https://www.youtube.com/praveenscience?sub_confirmation=1), if you haven't already subscribed and share it with your friends too.

**Comment by subhav13** [comment]
Can you please add Hacktoberfest approved label? Will be really glad. Also, already subscribed to your youtube channel.

**Comment by praveenscience** [comment]
@subhav13 That's not needed as the whole repo is under hacktoberfest and hacktoberfest2020 label... Does it not show in your hacktoberfest dashboard?

**Pull request merged**
