### PR TITLE
Updated readme

### PR DESCRIPTION
**Pull request by PranavViswanathan**
* Attend zoom meetings automatically:  Using the pyautogui to write a program that automatically logs the user into a zoom meeting when the username and password are given
* Code review platform (using the tkinter) : Making a UI that can run a program given by the user in the interface using the tkinter and subprocess logic.
* First aid app: An app that will guide a person in administering the required medical aid in an emergency.
* Parking ticket app : An app that can verify if the given parking ticket is correct (many [parking tickets have incorrect info and can be contested).

### CODE REVIEW

**Review by praveenscience — APPROVED** [review]
👍

**Review by praveenscience — APPROVED** [review]
👍

**Comment by praveenscience** [comment]
Thanks for your contribution. Optional Request: [Subscribe to my **YouTube Channel**](https://www.youtube.com/praveenscience?sub_confirmation=1), if you haven't already subscribed and share it with your friends too.

**Comment by PranavViswanathan** [comment]
Sorry about the Grammer, got a little exited

**Comment by praveenscience** [comment]
No worries, that's perfectly fine... Awesome, keep up the good work.

**Pull request merged**
