### PR TITLE
Added PetClinic By Springboot using java

### PR DESCRIPTION
**Pull request by ishitaojha**
Updated readme and added a project

### CODE REVIEW

**Review by praveenscience — APPROVED** [review]
👍

**Comment by praveenscience** [comment]
Thank you so much! 🎉

**Comment by praveenscience** [comment]
Thank you so much! 🎉  @ishitaojha You're the best! Would you like to be featured in a Live Stream? Shall we please collab? Connect with me on [**LinkedIn**](https://www.linkedin.com/in/praveentech/). 🎉

**Comment by ishitaojha** [comment]
You're so kind thank you so much :)

**Pull request merged**
