### PR TITLE
7 Python Project Idea Added

### PR DESCRIPTION
**Pull request by SamarpanCoder2002**
Some of them are unique ideas and I already Implement them Successfully... More Project Ideas will be added soon...
Hope you merge this pull request...

### CODE REVIEW

**Comment by praveenscience** [comment]
Let me check this and update you! Thanks a lot.

**Comment by SamarpanCoder2002** [comment]
> Ok Check it ..No prb

**Comment by SamarpanCoder2002** [comment]
Please Merge my pull request...If any problem occurs...you can freely tell me...

**Review by praveenscience — APPROVED** [review]
@SamarpanCoder2002 Looks cool man. Thanks.

**Comment by praveenscience** [comment]
Thanks for your contribution. Optional Request: [Subscribe to my **YouTube Channel**](https://www.youtube.com/praveenscience?sub_confirmation=1), if you haven't already subscribed and share it with your friends too.

**Comment by SamarpanCoder2002** [comment]
> Thanks for your contribution. Optional Request: [Subscribe to my **YouTube Channel**](https://www.youtube.com/praveenscience?sub_confirmation=1), if you haven't already subscribed and share it with your friends too.

Thanks for merge..

**Pull request merged**
