### PR TITLE
Added some ideas

### PR DESCRIPTION
**Pull request by aayushi221**

### CODE REVIEW

**Comment by aayushi221** [comment]
@praveenscience please check my pull request

**Comment by praveenscience** [comment]
Let me update it and check. 🔥

**Review by praveenscience — APPROVED** [review]
👍

**Comment by praveenscience** [comment]
Thanks for your contribution. Optional Request: [Subscribe to my **YouTube Channel**](https://www.youtube.com/praveenscience?sub_confirmation=1), if you haven't already subscribed and share it with your friends too.

**Pull request merged**
