### PR TITLE
Added a project in Python

### PR DESCRIPTION
**Pull request by ishitaojha**
Project to create an Audiobook using Python

### CODE REVIEW

**Review by praveenscience — APPROVED** [review]
👍

**Review by praveenscience — APPROVED** [review]
👍

**Comment by praveenscience** [comment]
@ishitaojha Thanks for your contribution. Optional Request: [Subscribe to my **YouTube Channel**](https://www.youtube.com/praveenscience?sub_confirmation=1), if you haven't already subscribed and share it with your friends too.

**Comment by ishitaojha** [comment]
Please add my PetClinic project too , I can even link the repo 
PS: surely I'll support your YouTube channel.❤✌

**Comment by praveenscience** [comment]
Thank you so much @ishitaojha! 🎉

**Comment by praveenscience** [comment]
You're the best! Would you like to be featured in a Live Stream? Shall we please collab? Connect with me on [**LinkedIn**](https://www.linkedin.com/in/praveentech/). 🎉

**Comment by ishitaojha** [comment]
Yeah why not that would be fun

**Pull request merged**
